// Generated by scripts/build_water_bodies.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::water_bodies {

struct Point {
  int32_t lat_e7;
  int32_t lon_e7;
};

// A run of shoreline. `closed` rings (small lakes fully in range)
// draw a segment from the last point back to the first.
struct Polyline {
  uint32_t start;
  uint16_t count;
  uint8_t closed;
};

constexpr size_t kPointCount = 54;
constexpr size_t kPolylineCount = 2;

extern const Point kPoints[];
extern const Polyline kPolylines[];

}  // namespace data::water_bodies
